noun1 = input("Insert 1st noun: ")
adjective1 = input("Insert 1st adjective: ")
noun2 = input("Insert 2nd noun: ")
noun3 = input("Insert 3rd noun: ")
adjective2 = input("Insert 2nd adjective: ")
adjective3 = input("Insert 3rd adjective: ")
name = input("Enter your name: ")

print(f"I went to {noun1} national park")
print(f"I saw a {adjective1} {noun2}")
print(f"The {noun2} was eating a {noun3}")
print(f"I was vey {adjective2} to have such a {adjective3} experience")
print(f"Hello {name}, I hope you enjoyed this game!")
