print(f"Hello World! This is my first git bash code!")
print("I am now able to push it to GitHub!")
print("I am going to create a pull request")
print("Check for a conflict without pulling from GitHub first")
print("Updated error successfully")
print("Git is interesting")
